config/routes.rb
Rails.application.routes.draw do
  get '/lists', to: 'lists#index'
  get '/lists/new', to: 'lists#new'
  post '/lists', to: 'lists#create'
  get '/lists/:id', to: 'lists#show', as: :list
  get '/lists/:list_id/bookmarks/new', to: 'bookmarks#new', as: :new_list_bookmark
  post '/lists/:list_id/bookmarks', to: 'bookmarks#create', as: :list_bookmarks
  delete '/bookmarks/:id', to: 'bookmarks#destroy', as: :bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  has_many_attached :photos
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_one_attached :photo

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created!'
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, photos: [])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list) # lists_path livecode
    else
      render 'lists/new' # render :new livecode
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name, :body, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="p-3">
  <h2>Create a Bookmark</h2>

  <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Choose a movie" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dvpavvw1u/image/upload/v1631278349/mason-kimbarovsky-X_d7m2r70bA-unsplash_xneysi.jpg);">
  <div class="container">
    <h1><strong>Movie Lists</strong></h1>
    <p>Create lists to add your favorite movies!</p>
    <%= link_to "ADD A NEW LIST", lists_new_path, class: 'btn btn-primary' %>
  </div>
</div>

<div>
  <h1>Movie Lists</h1>
</div>


<div>
  <ul class="fa-ul">
      <% @lists.each do |list| %>
        <li><span class="fa-li"><i class="fas fa-film"></i></span>
            <%= link_to list.name, list_path(list) %>
        </li>
      <%end%>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="p-3">
  <h2>Create a List</h2>

  <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
       <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div>
  <h2><%= @list.name %></h2>

<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
  <% else %>
  <p> There is no movies here!</p>
<% end %>



  <ul>
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
      <li >
     <strong><%= movie.title %></strong> |
      <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Delete #{movie.title.upcase} from your list?" } do %>
      <i class="far fa-trash-alt"></i>
      <% end %>
      <br>

      <% bookmark.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>

      <em><%= bookmark.comment %></em>
      </li>
    <%end%>
  </ul>
</div>


<div>
  <%= link_to "ADD A BOOKMARK", new_list_bookmark_path(@list), class: 'btn btn-primary' %>
     <br>
     <br>
  <%= link_to "BACK TO LISTS", lists_path %>
</div>